#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Start of 100 Variable Application\n");    // This is the start of all 100 variables. this will create numbers from 1-100. printf will later display them
    int ValueOne = 1;
    int ValueTwo = 2;
    int ValueThree = 3;
    int ValueFour = 4;
    int ValueFive = 5;
    int ValueSix = 6;
    int ValueSeven = 7;
    int ValueEight = 8;
    int ValueNine = 9;
    int ValueTen = 10;
    int ValueEleven = 11;
    int ValueTwelve = 12;
    int ValueThirteen = 13;
    int ValueFourteen = 14;
    int ValueFifteen = 15;
    int ValueSixteen = 16;
    int ValueSeventeen = 17;
    int ValueEighteen = 18;
    int ValueNineteen = 19;
    int ValueTwenty = 20;
    int ValueTwentyone = 21;
    int ValueTwentytwo = 22;
    int ValueTwentythree = 23;
    int ValueTwentyfour = 24;
    int ValueTwentyfive = 25;
    int ValueTwentysix = 26;
    int ValueTwentyseven = 27;
    int ValueTwentyeight = 28;
    int ValueTwentynine = 29;
    int ValueThirty = 30;
    int ValueThirtyone = 31;
    int ValueThirtytwo = 32;
    int ValueThirtythree = 33;
    int ValueThirtyfour = 34;
    int ValueThirtyfive = 35;
    int ValueThirtysix = 36;
    int ValueThirtyseven = 37;
    int ValueThirtyeight = 38;
    int ValueThirtynine = 39;
    int ValueFourty = 40;
    int ValueFourtyone = 41;
    int ValueFourtytwo = 42;
    int ValueFourtythree = 43;
    int ValueFourtyfour = 44;
    int ValueFourtyfive = 45;
    int ValueFourtysix = 46;
    int ValueFourtyseven = 47;
    int ValueFourtyeight = 48;
    int ValueFourtynine = 49;
    int ValueFifty = 50;
    int ValueFiftyone = 51;
    int ValueFiftytwo = 52;
    int ValueFiftythree = 53;
    int ValueFiftyfour = 54;
    int ValueFiftyfive = 55;
    int ValueFiftysix = 56;
    int ValueFiftyseven = 57;
    int ValueFiftyeight = 58;
    int ValueFiftynine = 59;
    int ValueSixty = 60;
    int ValueSixtyone = 61;
    int ValueSixtytwo = 62;
    int ValueSixtythree = 63;
    int ValueSixtyfour = 64;
    int ValueSixtyfive = 65;
    int ValueSixtysix = 66;
    int ValueSixtyseven = 67;
    int ValueSixtyeight = 68;
    int ValueSixtynine = 69;
    int ValueSeventy = 70;
    int ValueSeventyone = 71;
    int ValueSeventytwo = 72;
    int ValueSeventythree = 73;
    int ValueSeventyfour = 74;
    int ValueSeventyfive = 75;
    int ValueSeventysix = 76;
    int ValueSeventyseven = 77;
    int ValueSeventyeight = 78;
    int ValueSeventynine = 79;
    int ValueEighty = 80;
    int ValueEightyone = 81;
    int ValueEightytwo = 82;
    int ValueEightythree = 83;
    int ValueEightyfour = 84;
    int ValueEightyfive = 85;
    int ValueEightysix = 86;
    int ValueEightyseven = 87;
    int ValueEightyeight = 88;
    int ValueEightynine = 89;
    int ValueNinety = 90;
    int ValueNinetyone = 91;
    int ValueNinetytwo = 92;
    int ValueNinetythree = 93;
    int ValueNinetyfour = 94;
    int ValueNinetyfive = 95;
    int ValueNinetysix = 96;
    int ValueNinetyseven = 97;
    int ValueNinetyeight = 98;
    int ValueNinetynine = 99;
    int ValueOneHundred = 100;
    printf("%d\n", ValueOne);   // the point where printing and displaying all 100 numbers starts
    printf("%d\n", ValueTwo);
    printf("%d\n", ValueThree);
    printf("%d\n", ValueFour);
    printf("%d\n", ValueFive);
    printf("%d\n", ValueSix);
    printf("%d\n", ValueSeven);
    printf("%d\n", ValueEight);
    printf("%d\n", ValueNine);
    printf("%d\n", ValueTen);
    printf("%d\n", ValueEleven);
    printf("%d\n", ValueTwelve);
    printf("%d\n", ValueThirteen);
    printf("%d\n", ValueFourteen);
    printf("%d\n", ValueFifteen);
    printf("%d\n", ValueSixteen);
    printf("%d\n", ValueSeventeen);
    printf("%d\n", ValueEighteen);
    printf("%d\n", ValueNineteen);
    printf("%d\n", ValueTwenty);
    printf("%d\n", ValueTwentyone);
    printf("%d\n", ValueTwentytwo);
    printf("%d\n", ValueTwentythree);
    printf("%d\n", ValueTwentyfour);
    printf("%d\n", ValueTwentyfive);
    printf("%d\n", ValueTwentysix);
    printf("%d\n", ValueTwentyseven);
    printf("%d\n", ValueTwentyeight);
    printf("%d\n", ValueTwentynine);
    printf("%d\n", ValueThirty);
    printf("%d\n", ValueThirtyone);
    printf("%d\n", ValueThirtytwo);
    printf("%d\n", ValueThirtythree);
    printf("%d\n", ValueThirtyfour);
    printf("%d\n", ValueThirtyfive);
    printf("%d\n", ValueThirtysix);
    printf("%d\n", ValueThirtyseven);
    printf("%d\n", ValueThirtyeight);
    printf("%d\n", ValueThirtynine);
    printf("%d\n", ValueFourty);
    printf("%d\n", ValueFourtyone);
    printf("%d\n", ValueFourtytwo);
    printf("%d\n", ValueFourtythree);
    printf("%d\n", ValueFourtyfour);
    printf("%d\n", ValueFourtyfive);
    printf("%d\n", ValueFourtysix);
    printf("%d\n", ValueFourtyseven);
    printf("%d\n", ValueFourtyeight);
    printf("%d\n", ValueFourtynine);
    printf("%d\n", ValueFifty);
    printf("%d\n", ValueFiftyone);
    printf("%d\n", ValueFiftytwo);
    printf("%d\n", ValueFiftythree);
    printf("%d\n", ValueFiftyfour);
    printf("%d\n", ValueFiftyfive);
    printf("%d\n", ValueFiftysix);
    printf("%d\n", ValueFiftyseven);
    printf("%d\n", ValueFiftyeight);
    printf("%d\n", ValueFiftynine);
    printf("%d\n", ValueSixty);
    printf("%d\n", ValueSixtyone);
    printf("%d\n", ValueSixtytwo);
    printf("%d\n", ValueSixtythree);
    printf("%d\n", ValueSixtyfour);
    printf("%d\n", ValueSixtyfive);
    printf("%d\n", ValueSixtysix);
    printf("%d\n", ValueSixtyseven);
    printf("%d\n", ValueSixtyeight);
    printf("%d\n", ValueSixtynine);
    printf("%d\n", ValueSeventy);
    printf("%d\n", ValueSeventyone);
    printf("%d\n", ValueSeventytwo);
    printf("%d\n", ValueSeventythree);
    printf("%d\n", ValueSeventyfour);
    printf("%d\n", ValueSeventyfive);
    printf("%d\n", ValueSeventysix);
    printf("%d\n", ValueSeventyseven);
    printf("%d\n", ValueSeventyeight);
    printf("%d\n", ValueSeventynine);
    printf("%d\n", ValueEighty);
    printf("%d\n", ValueEightyone);
    printf("%d\n", ValueEightytwo);
    printf("%d\n", ValueEightythree);
    printf("%d\n", ValueEightyfour);
    printf("%d\n", ValueEightyfive);
    printf("%d\n", ValueEightysix);
    printf("%d\n", ValueEightyseven);
    printf("%d\n", ValueEightyeight);
    printf("%d\n", ValueEightynine);
    printf("%d\n", ValueNinety);
    printf("%d\n", ValueNinetyone);
    printf("%d\n", ValueNinetytwo);
    printf("%d\n", ValueNinetythree);
    printf("%d\n", ValueNinetyfour);
    printf("%d\n", ValueNinetyfive);
    printf("%d\n", ValueNinetysix);
    printf("%d\n", ValueNinetyseven);
    printf("%d\n", ValueNinetyeight);
    printf("%d\n", ValueNinetynine);
    printf("%d\n", ValueOneHundred);

    return 0;
}
